name: Deploy to EC2

on:
  push:
    branches: [main]   # Triggers on every push to main

jobs:
  deploy:
    runs-on: Amzon-linux-2023

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}        # Your EC2 public IP
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}       # Your .pem key contents
          script: |
            # Copy the new HTML file
            sudo cp /tmp/index.html /var/www/html/index.html
            sudo systemctl reload nginx
            echo "Deployment complete!"

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app/index.html"
          target: "/tmp/"
